name: Bytebase-SQL-Review
description: 'Parse and check the SQL statement according to the SQL review rules'
inputs:
  override-file-path:
    description: 'SQL check configuration override file path. Required if the template is not specified.'
    required: false
    default: ""
  database-type:
    description: 'The database type, should be one of "MYSQL", "POSTGRES" or "TIDB".'
    required: true
  template-id:
    description: 'The SQL check template id, required if the override is not specified. Should be one of "bb.sql-review.prod", "bb.sql-review.dev".'
    required: false
  ignore-files:
    description: 'Ignore changes to this list of files.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v23.2
      with:
        files: |
          **/*.sql
        files_ignore: ${{ inputs.ignore-files }}
    - name: SQL Review
      run: |
        ./entrypoint.sh --files="${{ steps.changed-files.outputs.all_changed_files }}" --database-type=${{ inputs.database-type }} --override-file="${{ inputs.override-file-path }}" --template-id="${{ inputs.template-id }}"
      shell: bash
branding:
  icon: "database"
  color: "gray-dark"
